import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Noto_Sans } from 'next/font/google';
import "./globals.scss";
import { SITE_NAME } from "@/constants/seo.constants";
import { Toaster } from "sonner";
import { Providers } from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const notoSans = Noto_Sans({
  weight: [ "300", "400", "500", "600", "700"],
  display: "swap",
  variable: "--font-noto-sans",
  subsets: ["cyrillic", "latin"],
  style: ["normal"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: SITE_NAME,
    template: `%s | ${SITE_NAME}`,
  },
  description: "Generated by TheSanchas",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ notoSans.className }`}>

        <Providers>{children} 
          <Toaster
            theme="dark"
            position="bottom-right"
            duration={1500}
        />
        </Providers>
      </body>
    </html>
  );
}
